version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www/html
      - ./docker/nginx/proxy_params:/etc/nginx/proxy_params
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available

  php:
    container_name: php
    build: .
    volumes:
      - ./back:/var/www/html
    command:
      - bash
      - -c
      - |
        composer install
        php-fpm
