version: '3'

services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_CORE_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXT_PORT}:5432"
    volumes:
      - ${DOCKER_FILES_PATH}/postgres/data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - './back:/var/www/html'
      - '${DOCKER_FILES_PATH}/nginx/proxy_params:/etc/nginx/proxy_params'
      - '${DOCKER_FILES_PATH}/nginx/conf.d:/etc/nginx/conf.d'
      - '${DOCKER_FILES_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '${DOCKER_FILES_PATH}/nginx/sites-available:/etc/nginx/sites-available'

  php:
    container_name: php
    build: .
    volumes:
      - ./back:/var/www/html
    environment:
      POSTGRES_DB: ${POSTGRES_CORE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - bash
      - -c
      - |
        composer install
        php bin/console --no-interaction doctrine:migrations:migrate
        php-fpm
