version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./site:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
