version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./site:/var/www/html
      - ./docker/nginx/default.conf

  postgres:
    container_name: postgres
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432"
